version: "3"

services:
  scraper:
    build: scraper
    command: npm start
    environment:
      - MEDIA_DIR=media
    volumes:
      - media:/app/media
      - ./scraper/src:/app/src

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: backend
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    links:
      - scraper
    depends_on:
      - db
    environment:
      DEBUG: "${DEBUG}"
      MEDIA_ROOT: "${MEDIA_ROOT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_HOST: "${DB_HOST}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"
      LOGFILE_LEVEL: "${LOGFILE_LEVEL}"
      LOGFILE_PATH: "${LOGFILE_PATH}"

volumes:
  postgres:
  media:
